// 此檔案由 build script 自動產生,請勿手動編輯
// 由 menu-raw.js 展開為四語言完整渲染格式

export const menuItems = [
  // ── 套餐 ───────────────────────────────────────────────────────────────
  {
    id: 'combo-001',
    category: 'combo',
    names: {
      zh: '經典烏骨雞塊餐',
      en: 'Classic Silkie Tender Combo',
      ja: '定番烏骨鶏テンダーセット',
      ko: '클래식 오골계 텐더 세트',
    },
    price: [
      { label: { zh: '原味', en: 'Original', ja: 'プレーン', ko: '오리지널' }, value: 220 },
      { label: { zh: '椒鹽', en: 'Pepper Salt', ja: '塩こしょう', ko: '페퍼 솔트' }, value: 230 },
    ],
    image: null,
    emoji: '🍗',
    tags: ['R'],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: {
      zh: '含 4 塊烏骨雞柳、薯條、招牌椒鹽、烏龍茶',
      en: 'Includes 4 silkie tenders, fries, signature pepper salt, oolong tea',
      ja: '烏骨鶏テンダー4本、フライドポテト、特製塩こしょう、ウーロン茶付き',
      ko: '오골계 텐더 4조각, 감자튀김, 시그니처 페퍼 솔트, 우롱차 포함',
    },
  },
  {
    id: 'combo-002',
    category: 'combo',
    names: {
      zh: '三塊輕食套餐',
      en: 'Three-Tender Light Combo',
      ja: '3本ライトセット',
      ko: '3조각 라이트 세트',
    },
    price: [{ label: null, value: 180 }],
    image: null,
    emoji: '🍱',
    tags: [],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: {
      zh: '3 塊烏骨雞柳、薯條、烏龍茶',
      en: '3 silkie tenders, fries, oolong tea',
      ja: '烏骨鶏テンダー3本、フライドポテト、ウーロン茶',
      ko: '오골계 텐더 3조각, 감자튀김, 우롱차',
    },
  },
  {
    id: 'combo-003',
    category: 'combo',
    names: {
      zh: '雞迷大份量套餐',
      en: 'Tender Lover XL Combo',
      ja: 'チキンマニアXLセット',
      ko: '치킨 매니아 XL 세트',
    },
    price: [{ label: null, value: 320 }],
    image: null,
    emoji: '🍳',
    tags: ['R'],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: {
      zh: '6 塊烏骨雞柳、薯條、雙醬、32oz 烏龍茶',
      en: '6 silkie tenders, fries, two sauces, 32oz oolong tea',
      ja: '烏骨鶏テンダー6本、フライドポテト、ソース2種、32ozウーロン茶',
      ko: '오골계 텐더 6조각, 감자튀김, 소스 2종, 32oz 우롱차',
    },
  },
  {
    id: 'combo-004',
    category: 'combo',
    names: {
      zh: '烏骨雞堡套餐',
      en: 'Silkie Chicken Burger Combo',
      ja: '烏骨鶏バーガーセット',
      ko: '오골계 버거 세트',
    },
    price: [
      { label: { zh: '原味', en: 'Original', ja: 'プレーン', ko: '오리지널' }, value: 200 },
      { label: { zh: '辣味', en: 'Spicy', ja: 'スパイシー', ko: '매운맛' }, value: 210 },
    ],
    image: null,
    emoji: '🍔',
    tags: ['1'],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: {
      zh: '烏骨雞腿堡、薯條、烏龍茶',
      en: 'Silkie chicken thigh burger, fries, oolong tea',
      ja: '烏骨鶏もも肉バーガー、フライドポテト、ウーロン茶',
      ko: '오골계 다리살 버거, 감자튀김, 우롱차',
    },
  },
  {
    id: 'combo-005',
    category: 'combo',
    names: {
      zh: '兒童歡樂餐',
      en: 'Kids Happy Meal',
      ja: 'キッズハッピーセット',
      ko: '키즈 해피 세트',
    },
    price: [{ label: null, value: 150 }],
    image: null,
    emoji: '🧒',
    tags: [],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: {
      zh: '2 塊烏骨雞柳、薯條、果汁,附小玩具',
      en: '2 silkie tenders, fries, juice — with a small toy',
      ja: '烏骨鶏テンダー2本、フライドポテト、ジュース、おもちゃ付き',
      ko: '오골계 텐더 2조각, 감자튀김, 주스, 작은 장난감 포함',
    },
  },

  // ── 加點 ───────────────────────────────────────────────────────────────
  {
    id: 'extra-001',
    category: 'extra',
    names: {
      zh: '單塊烏骨雞柳',
      en: 'Single Silkie Tender',
      ja: '烏骨鶏テンダー単品',
      ko: '오골계 텐더 단품',
    },
    price: [{ label: null, value: 45 }],
    image: null,
    emoji: '🍗',
    tags: ['R'],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'extra-002',
    category: 'extra',
    names: {
      zh: '招牌椒鹽風味醬',
      en: 'Signature Pepper Salt Sauce',
      ja: '特製塩こしょうソース',
      ko: '시그니처 페퍼 솔트 소스',
    },
    price: [{ label: null, value: 20 }],
    image: null,
    emoji: '🧂',
    tags: ['1'],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: {
      zh: '微辣,小份杯裝',
      en: 'Mild spicy, small cup',
      ja: '少し辛い、小カップ',
      ko: '약간 매운, 소컵',
    },
  },
  {
    id: 'extra-003',
    category: 'extra',
    names: {
      zh: '黃金酥炸薯條',
      en: 'Golden Crinkle Fries',
      ja: 'ゴールデンクリンクルポテト',
      ko: '골든 크링클 감자튀김',
    },
    price: [
      { label: { zh: '大', en: 'Large', ja: '大', ko: '라지' }, value: 80 },
      { label: { zh: '小', en: 'Small', ja: '小', ko: '스몰' }, value: 50 },
    ],
    image: null,
    emoji: '🍟',
    tags: [],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'extra-004',
    category: 'extra',
    names: {
      zh: '蒜香吐司',
      en: 'Garlic Toast',
      ja: 'ガーリックトースト',
      ko: '갈릭 토스트',
    },
    price: [{ label: null, value: 40 }],
    image: null,
    emoji: '🥪',
    tags: [],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'extra-005',
    category: 'extra',
    names: {
      zh: '涼拌高麗菜',
      en: 'Coleslaw',
      ja: 'コールスロー',
      ko: '콜슬로',
    },
    price: [{ label: null, value: 40 }],
    image: null,
    emoji: '🥗',
    tags: ['V5'],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: {
      zh: '含蒜,屬五辛素',
      en: 'Contains garlic — plant-based with allium',
      ja: 'にんにく入り、五葷あり精進',
      ko: '마늘 포함, 오신채 포함 채식',
    },
  },

  // ── 飲料 ───────────────────────────────────────────────────────────────
  {
    id: 'drink-001',
    category: 'drink',
    names: {
      zh: '古早味檸檬紅茶',
      en: 'Classic Lemon Black Tea',
      ja: '昔ながらのレモン紅茶',
      ko: '옛날식 레몬 홍차',
    },
    price: [
      { label: { zh: '杯', en: 'Cup', ja: 'カップ', ko: '컵' }, value: 40 },
      { label: { zh: '壺', en: 'Pitcher', ja: 'ピッチャー', ko: '주전자' }, value: 120 },
    ],
    image: null,
    emoji: '🍋',
    tags: [],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'drink-002',
    category: 'drink',
    names: {
      zh: '黑糖烏龍',
      en: 'Brown Sugar Oolong',
      ja: '黒糖ウーロン',
      ko: '흑당 우롱',
    },
    price: [
      { label: { zh: '杯', en: 'Cup', ja: 'カップ', ko: '컵' }, value: 45 },
      { label: { zh: '壺', en: 'Pitcher', ja: 'ピッチャー', ko: '주전자' }, value: 130 },
    ],
    image: null,
    emoji: '🧋',
    tags: ['R'],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'drink-003',
    category: 'drink',
    names: {
      zh: '古法冬瓜茶',
      en: 'Traditional Winter Melon Tea',
      ja: '昔ながらの冬瓜茶',
      ko: '전통 동과차',
    },
    price: [
      { label: { zh: '杯', en: 'Cup', ja: 'カップ', ko: '컵' }, value: 35 },
      { label: { zh: '壺', en: 'Pitcher', ja: 'ピッチャー', ko: '주전자' }, value: 110 },
    ],
    image: null,
    emoji: '🍵',
    tags: [],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'drink-004',
    category: 'drink',
    names: {
      zh: '鮮榨檸檬汁',
      en: 'Fresh-Squeezed Lemonade',
      ja: '生搾りレモネード',
      ko: '생 레몬 주스',
    },
    price: [{ label: null, value: 60 }],
    image: null,
    emoji: '🍋',
    tags: [],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: {
      zh: '無糖可選',
      en: 'Sugar-free option available',
      ja: '無糖を選択可',
      ko: '무가당 선택 가능',
    },
  },

  // ── 外帶分享 ───────────────────────────────────────────────────────────
  {
    id: 'share-001',
    category: 'share',
    names: {
      zh: '25 塊分享桶',
      en: '25-Piece Sharing Bucket',
      ja: '25本シェアバケット',
      ko: '25조각 셰어 버킷',
    },
    price: [{ label: null, value: 850 }],
    image: null,
    emoji: '🪣',
    tags: ['R'],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: {
      zh: '附 2 份招牌醬',
      en: 'Includes 2 signature sauces',
      ja: '特製ソース2個付き',
      ko: '시그니처 소스 2개 포함',
    },
  },
  {
    id: 'share-002',
    category: 'share',
    names: {
      zh: '50 塊團體桶',
      en: '50-Piece Group Bucket',
      ja: '50本グループバケット',
      ko: '50조각 그룹 버킷',
    },
    price: [{ label: null, value: 1600 }],
    image: null,
    emoji: '🍱',
    tags: [],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: {
      zh: '附 4 份招牌醬',
      en: 'Includes 4 signature sauces',
      ja: '特製ソース4個付き',
      ko: '시그니처 소스 4개 포함',
    },
  },
  {
    id: 'share-003',
    category: 'share',
    names: {
      zh: '100 塊派對桶',
      en: '100-Piece Party Bucket',
      ja: '100本パーティーバケット',
      ko: '100조각 파티 버킷',
    },
    price: [{ label: null, value: 'market' }],
    image: null,
    emoji: '🎉',
    tags: [],
    desc: { zh: '', en: '', ja: '', ko: '' },
    note: {
      zh: '需提前 24 小時預訂',
      en: 'Reserve 24 hours in advance',
      ja: '24時間前のご予約が必要',
      ko: '24시간 전 예약 필수',
    },
  },
]

export const categories = [
  { id: 'combo', label: { zh: '套餐', en: 'Combos', ja: 'セット', ko: '세트' } },
  { id: 'extra', label: { zh: '加點', en: 'Extras', ja: 'サイド', ko: '추가' } },
  { id: 'drink', label: { zh: '飲料', en: 'Drinks', ja: 'ドリンク', ko: '음료' } },
  { id: 'share', label: { zh: '外帶分享', en: 'Sharing', ja: 'シェア', ko: '공유' } },
]

export const tagInfo = {
  R:  { icon: '⭐',  label: { zh: '本店推薦',  en: 'Recommended',          ja: 'おすすめ',         ko: '추천' } },
  '1':{ icon: '🌶️',  label: { zh: '小辣',     en: 'Mild Spicy',           ja: '少し辛い',         ko: '약간 매운' } },
  '2':{ icon: '🌶️🌶️', label: { zh: '中辣',    en: 'Medium Spicy',         ja: '中辛',             ko: '보통 매운' } },
  '3':{ icon: '🔥',  label: { zh: '大辣',     en: 'Very Spicy',           ja: '激辛',             ko: '매우 매운' } },
  P:  { icon: '🐷',  label: { zh: '含豬肉',   en: 'Contains Pork',        ja: '豚肉入り',         ko: '돼지고기 포함' } },
  B:  { icon: '🐂',  label: { zh: '含牛肉',   en: 'Contains Beef',        ja: '牛肉入り',         ko: '소고기 포함' } },
  L:  { icon: '🐑',  label: { zh: '含羊肉',   en: 'Contains Lamb',        ja: 'ラム入り',         ko: '양고기 포함' } },
  V:  { icon: '🥬',  label: { zh: '素食',     en: 'Vegetarian',           ja: 'ベジタリアン',     ko: '채식' } },
  V5: { icon: '🧄',  label: { zh: '五辛素',   en: 'Plant-based w/ Allium',ja: '五葷あり精進',     ko: '오신채 포함 채식' } },
  H:  { icon: '☪️',  label: { zh: '清真認證', en: 'Halal Certified',      ja: 'ハラール認証',     ko: '할랄 인증' } },
}

export const shopInfo = {
  name: {
    zh: '烏骨雞炸雞',
    en: 'Silkie Fried Chicken',
    ja: '烏骨鶏フライドチキン',
    ko: '오골계 후라이드',
  },
  address: {
    zh: '我家',
    en: 'My Home',
    ja: '自宅',
    ko: '우리집',
  },
  phone: '0912345678',
  hours: {
    zh: '營業時間 17:00 – 20:00 ・ 公休不固定 ・ 僅外送無內用',
    en: 'Open 17:00 – 20:00 · Irregular closures · Delivery only, no dine-in',
    ja: '営業 17:00 – 20:00 ・ 不定休 ・ 配達のみ、店内飲食なし',
    ko: '영업 17:00 – 20:00 · 비정기 휴무 · 배달 전용, 매장 식사 불가',
  },
  ui: {
    callShop:    { zh: '撥打電話', en: 'Call Shop',     ja: '電話する',     ko: '전화하기' },
    address:     { zh: '地址',     en: 'Address',       ja: '住所',         ko: '주소' },
    phone:       { zh: '電話',     en: 'Phone',         ja: '電話',         ko: '전화' },
    hours:       { zh: '用餐資訊', en: 'Hours & Info',  ja: 'ご利用情報',   ko: '이용 안내' },
    market:      { zh: '時價',     en: 'Market Price',  ja: '時価',         ko: '시가' },
    description: { zh: '說明',     en: 'Description',   ja: '説明',         ko: '설명' },
    notes:       { zh: '備註',     en: 'Notes',         ja: '備考',         ko: '비고' },
    close:       { zh: '關閉',     en: 'Close',         ja: '閉じる',       ko: '닫기' },
    pinchHint:   { zh: '雙指縮放', en: 'Pinch to zoom', ja: 'ピンチで拡大', ko: '핀치 확대' },
  },
}
